/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author salma
 */
public class DateTimePanel extends javax.swing.JPanel {

    private int month;
    private int year;
    
    /**
     * Creates new form DateTimePanel
     */
    public DateTimePanel() {
        initComponents();
        setDateTime();
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(60000);
                    } catch (InterruptedException e) {
                        System.err.println(e);
                    }
                    setDateTime();
                }
            }
        }).start();
        
    }
    
    private void setDateTime()
    {
        
        Date date = new Date();
        SimpleDateFormat tf = new SimpleDateFormat("hh mm aa");
        SimpleDateFormat df = new SimpleDateFormat("EEEE, MMMM dd");
        String time = tf.format(date);
        hoursText.setText(time.split(" ")[0]);
        minutesText.setText(time.split(" ")[1]);
        daytimeText.setText(time.split(" ")[2]);
        dateText.setText(df.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new customSwingComponents.PanelBorder();
        dateTimeLabel = new javax.swing.JLabel();
        clockPanel = new javax.swing.JPanel();
        panelBorder4 = new customSwingComponents.PanelBorder();
        minutesText = new javax.swing.JLabel();
        panelBorder5 = new customSwingComponents.PanelBorder();
        hoursText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        daytimeText = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(20, 18, 24));
        panelBorder1.setPreferredSize(new java.awt.Dimension(452, 219));
        panelBorder1.setRadius(50);

        dateTimeLabel.setBackground(new java.awt.Color(254, 247, 255));
        dateTimeLabel.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        dateTimeLabel.setForeground(new java.awt.Color(202, 196, 208));
        dateTimeLabel.setText("date & time");

        clockPanel.setOpaque(false);

        panelBorder4.setBackground(new java.awt.Color(54, 52, 59));
        panelBorder4.setRadius(30);

        minutesText.setBackground(new java.awt.Color(254, 247, 255));
        minutesText.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        minutesText.setForeground(new java.awt.Color(254, 247, 255));
        minutesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minutesText.setText("00");

        javax.swing.GroupLayout panelBorder4Layout = new javax.swing.GroupLayout(panelBorder4);
        panelBorder4.setLayout(panelBorder4Layout);
        panelBorder4Layout.setHorizontalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(minutesText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelBorder4Layout.setVerticalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(minutesText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelBorder5.setBackground(new java.awt.Color(79, 55, 139));
        panelBorder5.setRadius(30);

        hoursText.setBackground(new java.awt.Color(254, 247, 255));
        hoursText.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        hoursText.setForeground(new java.awt.Color(254, 247, 255));
        hoursText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoursText.setText("20");

        javax.swing.GroupLayout panelBorder5Layout = new javax.swing.GroupLayout(panelBorder5);
        panelBorder5.setLayout(panelBorder5Layout);
        panelBorder5Layout.setHorizontalGroup(
            panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hoursText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelBorder5Layout.setVerticalGroup(
            panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hoursText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel4.setBackground(new java.awt.Color(254, 247, 255));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 247, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");

        daytimeText.setBackground(new java.awt.Color(254, 247, 255));
        daytimeText.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        daytimeText.setForeground(new java.awt.Color(254, 247, 255));
        daytimeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daytimeText.setText("P.m.");

        javax.swing.GroupLayout clockPanelLayout = new javax.swing.GroupLayout(clockPanel);
        clockPanel.setLayout(clockPanelLayout);
        clockPanelLayout.setHorizontalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelBorder5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daytimeText, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        clockPanelLayout.setVerticalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(daytimeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clockPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addComponent(panelBorder5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBorder4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        dateText.setBackground(new java.awt.Color(254, 247, 255));
        dateText.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        dateText.setForeground(new java.awt.Color(254, 247, 255));
        dateText.setText("Mon, Aug 17");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTimeLabel)
                            .addComponent(dateText))))
                .addGap(56, 56, 56))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clockPanel;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JLabel daytimeText;
    private javax.swing.JLabel hoursText;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel minutesText;
    private customSwingComponents.PanelBorder panelBorder1;
    private customSwingComponents.PanelBorder panelBorder4;
    private customSwingComponents.PanelBorder panelBorder5;
    // End of variables declaration//GEN-END:variables
}
