/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import DatabaseHelpers.DatabaseHelper;
import models.NoteModel;

/**
 *
 * @author salma
 */
public class Headerpanel extends javax.swing.JPanel {
    //private HomeFrame homeFrame;

    /**
     * Creates new form Headerpanel
     */
    
    public Headerpanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new customSwingComponents.PanelBorder();
        addNoteBtn = new com.markbean.notes.customGUIComponents.RoundedButton();

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(20, 18, 24));

        addNoteBtn.setBackground(new java.awt.Color(103, 80, 164));
        addNoteBtn.setBorder(null);
        addNoteBtn.setForeground(new java.awt.Color(103, 80, 164));
        addNoteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        addNoteBtn.setBorderColor(new java.awt.Color(103, 80, 164));
        addNoteBtn.setColor(new java.awt.Color(103, 80, 164));
        addNoteBtn.setColorClick(new java.awt.Color(102, 0, 153));
        addNoteBtn.setColorOver(new java.awt.Color(51, 0, 102));
        addNoteBtn.setRadius(15);
        addNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteBtnActionPerformed
        //homeFrame.setPage(new NotePanel(new NoteModel(), homeFrame));
        HomeFrame.Instance.setPage(new NotePanel(new NoteModel()));
       
    }//GEN-LAST:event_addNoteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.markbean.notes.customGUIComponents.RoundedButton addNoteBtn;
    private customSwingComponents.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
