/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import customSwingComponents.ScrollBar;
import java.awt.Color;

/**
 *
 * @author salma
 */
public class NotePanel extends javax.swing.JPanel {

    /**
     * Creates new form NotePanel
     */
    public NotePanel() {
        initComponents();
        contentScroll.setVerticalScrollBar(new ScrollBar());
        contentScroll.getVerticalScrollBar().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new customSwingComponents.PanelBorder();
        buttonsPanel = new javax.swing.JPanel();
        screenshotBtn = new customSwingComponents.GradientButton();
        todoBtn = new customSwingComponents.GradientButton();
        paintBtn = new customSwingComponents.GradientButton();
        homeBtn = new customSwingComponents.GradientButton();
        lastEditedPanel = new javax.swing.JPanel();
        creationDate = new javax.swing.JLabel();
        createdLabel = new javax.swing.JLabel();
        dateCreatedPanel = new javax.swing.JPanel();
        creationDate1 = new javax.swing.JLabel();
        createdLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        contentScroll = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        buttonsPanel.setOpaque(false);

        screenshotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cameraIcon.png"))); // NOI18N
        screenshotBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        screenshotBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        screenshotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenshotBtnActionPerformed(evt);
            }
        });

        todoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/todoIcon.png"))); // NOI18N
        todoBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        todoBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        todoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoBtnActionPerformed(evt);
            }
        });

        paintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paintIcon.png"))); // NOI18N
        paintBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        paintBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        paintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintBtnActionPerformed(evt);
            }
        });

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcon.png"))); // NOI18N
        homeBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        homeBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(screenshotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenshotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lastEditedPanel.setOpaque(false);

        creationDate.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        creationDate.setForeground(new java.awt.Color(153, 153, 153));
        creationDate.setText("17/2/2024, 3:00 a.m.");

        createdLabel.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        createdLabel.setForeground(new java.awt.Color(153, 153, 153));
        createdLabel.setText("Last Edited:");

        javax.swing.GroupLayout lastEditedPanelLayout = new javax.swing.GroupLayout(lastEditedPanel);
        lastEditedPanel.setLayout(lastEditedPanelLayout);
        lastEditedPanelLayout.setHorizontalGroup(
            lastEditedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastEditedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lastEditedPanelLayout.setVerticalGroup(
            lastEditedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastEditedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lastEditedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creationDate)
                    .addComponent(createdLabel))
                .addContainerGap())
        );

        dateCreatedPanel.setOpaque(false);

        creationDate1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        creationDate1.setForeground(new java.awt.Color(153, 153, 153));
        creationDate1.setText("17/2/2024, 3:00 a.m.");

        createdLabel1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        createdLabel1.setForeground(new java.awt.Color(153, 153, 153));
        createdLabel1.setText("created:");

        javax.swing.GroupLayout dateCreatedPanelLayout = new javax.swing.GroupLayout(dateCreatedPanel);
        dateCreatedPanel.setLayout(dateCreatedPanelLayout);
        dateCreatedPanelLayout.setHorizontalGroup(
            dateCreatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateCreatedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createdLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dateCreatedPanelLayout.setVerticalGroup(
            dateCreatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateCreatedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateCreatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creationDate1)
                    .addComponent(createdLabel1))
                .addContainerGap())
        );

        title.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(208, 208, 208));
        title.setText("Title");

        contentScroll.setBorder(null);
        contentScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        content.setColumns(20);
        content.setLineWrap(true);
        content.setRows(5);
        content.setWrapStyleWord(true);
        content.setBorder(null);
        contentScroll.setViewportView(content);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(lastEditedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(dateCreatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(847, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(contentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateCreatedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastEditedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(contentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void paintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintBtnActionPerformed

    private void todoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todoBtnActionPerformed

    private void screenshotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenshotBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screenshotBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JTextArea content;
    private javax.swing.JScrollPane contentScroll;
    private javax.swing.JLabel createdLabel;
    private javax.swing.JLabel createdLabel1;
    private javax.swing.JLabel creationDate;
    private javax.swing.JLabel creationDate1;
    private javax.swing.JPanel dateCreatedPanel;
    private customSwingComponents.GradientButton homeBtn;
    private javax.swing.JPanel lastEditedPanel;
    private customSwingComponents.GradientButton paintBtn;
    private customSwingComponents.PanelBorder panelBorder1;
    private customSwingComponents.GradientButton screenshotBtn;
    private javax.swing.JLabel title;
    private customSwingComponents.GradientButton todoBtn;
    // End of variables declaration//GEN-END:variables
}
