/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import customSwingComponents.ScrollBar;
import java.awt.Color;
import models.NoteModel;

/**
 *
 * @author salma
 */
public class NotePreviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotePanel
     */
    public NotePreviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panelBorder1 = new customSwingComponents.PanelBorder();
        lastEditedDatePanel = new javax.swing.JPanel();
        createdLabel1 = new javax.swing.JLabel();
        creationDate1 = new javax.swing.JLabel();
        createdDatePanel = new javax.swing.JPanel();
        createdLabel = new javax.swing.JLabel();
        creationDate = new javax.swing.JLabel();
        noteContent = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        editBtn = new customSwingComponents.GradientButton();
        noteTitle = new javax.swing.JLabel();
        deleteNoteBtn = new customSwingComponents.GradientButton();

        jToggleButton1.setText("jToggleButton1");

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setRadius(30);

        lastEditedDatePanel.setOpaque(false);

        createdLabel1.setBackground(new java.awt.Color(204, 204, 204));
        createdLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createdLabel1.setForeground(new java.awt.Color(153, 153, 153));
        createdLabel1.setText("Last Edited:");

        creationDate1.setBackground(new java.awt.Color(255, 255, 255));
        creationDate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creationDate1.setForeground(new java.awt.Color(153, 153, 153));
        creationDate1.setText("24/3/2024, 3:30 p.m.");

        javax.swing.GroupLayout lastEditedDatePanelLayout = new javax.swing.GroupLayout(lastEditedDatePanel);
        lastEditedDatePanel.setLayout(lastEditedDatePanelLayout);
        lastEditedDatePanelLayout.setHorizontalGroup(
            lastEditedDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastEditedDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lastEditedDatePanelLayout.setVerticalGroup(
            lastEditedDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastEditedDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lastEditedDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdLabel1)
                    .addComponent(creationDate1))
                .addContainerGap())
        );

        createdDatePanel.setOpaque(false);

        createdLabel.setBackground(new java.awt.Color(204, 204, 204));
        createdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createdLabel.setForeground(new java.awt.Color(153, 153, 153));
        createdLabel.setText("created: ");

        creationDate.setBackground(new java.awt.Color(255, 255, 255));
        creationDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creationDate.setForeground(new java.awt.Color(153, 153, 153));
        creationDate.setText("24/3/2024, 3:30 p.m.");

        javax.swing.GroupLayout createdDatePanelLayout = new javax.swing.GroupLayout(createdDatePanel);
        createdDatePanel.setLayout(createdDatePanelLayout);
        createdDatePanelLayout.setHorizontalGroup(
            createdDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createdDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        createdDatePanelLayout.setVerticalGroup(
            createdDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createdDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createdDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdLabel)
                    .addComponent(creationDate))
                .addContainerGap())
        );

        noteContent.setColumns(20);
        noteContent.setRows(5);
        noteContent.setWrapStyleWord(true);
        noteContent.setBorder(null);

        jPanel1.setOpaque(false);

        editBtn.setBorder(null);
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editIcon.png"))); // NOI18N
        editBtn.setToolTipText("home");
        editBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        editBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        noteTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        noteTitle.setForeground(new java.awt.Color(204, 204, 204));
        noteTitle.setText("Title");

        deleteNoteBtn.setBorder(null);
        deleteNoteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tabler_trash.png"))); // NOI18N
        deleteNoteBtn.setToolTipText("home");
        deleteNoteBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        deleteNoteBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        deleteNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNoteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noteTitle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(createdDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastEditedDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(noteContent, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createdDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastEditedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteContent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        //goto home
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNoteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteNoteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createdDatePanel;
    private javax.swing.JLabel createdLabel;
    private javax.swing.JLabel createdLabel1;
    private javax.swing.JLabel creationDate;
    private javax.swing.JLabel creationDate1;
    private customSwingComponents.GradientButton deleteNoteBtn;
    private customSwingComponents.GradientButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel lastEditedDatePanel;
    private javax.swing.JTextArea noteContent;
    private javax.swing.JLabel noteTitle;
    private customSwingComponents.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
