/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import customSwingComponents.ScrollBar;
import models.TaskModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author salma
 */
public class NotesPreviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ToDoPanel
     */
    public NotesPreviewPanel() {
        initComponents();
        notesPreviewScrollPanel.setVerticalScrollBar(new ScrollBar());
        notesPreviewScrollPanel.getVerticalScrollBar().setBackground(getBackground());
        notesPreviewScrollPanel.getViewport().setOpaque(false);
        notesPreviewScrollPanel.setViewportBorder(null);
        notesPreviewList.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));

        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());
        notesPreviewList.add(new NotePreviewPanel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new customSwingComponents.PanelBorder();
        notesPreviewScrollPanel = new javax.swing.JScrollPane();
        notesPreviewList = new javax.swing.JPanel();

        panelBorder1.setBackground(new java.awt.Color(20, 18, 24));
        panelBorder1.setForeground(new java.awt.Color(20, 18, 24));
        panelBorder1.setRadius(50);

        notesPreviewScrollPanel.setBackground(new java.awt.Color(20, 18, 24));
        notesPreviewScrollPanel.setBorder(null);
        notesPreviewScrollPanel.setForeground(new java.awt.Color(20, 18, 24));
        notesPreviewScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        notesPreviewScrollPanel.setOpaque(false);

        notesPreviewList.setBackground(new java.awt.Color(20, 18, 24));
        notesPreviewList.setForeground(new java.awt.Color(20, 18, 24));
        notesPreviewList.setOpaque(false);

        javax.swing.GroupLayout notesPreviewListLayout = new javax.swing.GroupLayout(notesPreviewList);
        notesPreviewList.setLayout(notesPreviewListLayout);
        notesPreviewListLayout.setHorizontalGroup(
            notesPreviewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        notesPreviewListLayout.setVerticalGroup(
            notesPreviewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        notesPreviewScrollPanel.setViewportView(notesPreviewList);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(notesPreviewScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(notesPreviewScrollPanel)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel notesPreviewList;
    private javax.swing.JScrollPane notesPreviewScrollPanel;
    private customSwingComponents.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
