/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import customSwingComponents.ScrollBar;
import java.awt.Color;

/**
 *
 * @author salma
 */
public class NotePanel extends javax.swing.JPanel {

    /**
     * Creates new form NotePanel
     */
    public NotePanel() {
        initComponents();
        contentAreaScrollPane.setVerticalScrollBar(new ScrollBar());
        contentAreaScrollPane.getVerticalScrollBar().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panelBorder1 = new customSwingComponents.PanelBorder();
        lastEditedDatePanel = new javax.swing.JPanel();
        createdLabel1 = new javax.swing.JLabel();
        creationDate1 = new javax.swing.JLabel();
        createdDatePanel = new javax.swing.JPanel();
        createdLabel = new javax.swing.JLabel();
        creationDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iconsPanel = new javax.swing.JPanel();
        todoBtn = new customSwingComponents.GradientButton();
        cameraBtn = new customSwingComponents.GradientButton();
        paintBtn = new customSwingComponents.GradientButton();
        menuBtn = new customSwingComponents.GradientButton();
        contentAreaScrollPane = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jToggleButton1.setText("jToggleButton1");

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        lastEditedDatePanel.setOpaque(false);

        createdLabel1.setBackground(new java.awt.Color(204, 204, 204));
        createdLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createdLabel1.setForeground(new java.awt.Color(153, 153, 153));
        createdLabel1.setText("Last Edited:");

        creationDate1.setBackground(new java.awt.Color(255, 255, 255));
        creationDate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creationDate1.setForeground(new java.awt.Color(153, 153, 153));
        creationDate1.setText("24/3/2024, 3:30 p.m.");

        javax.swing.GroupLayout lastEditedDatePanelLayout = new javax.swing.GroupLayout(lastEditedDatePanel);
        lastEditedDatePanel.setLayout(lastEditedDatePanelLayout);
        lastEditedDatePanelLayout.setHorizontalGroup(
            lastEditedDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastEditedDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        lastEditedDatePanelLayout.setVerticalGroup(
            lastEditedDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastEditedDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lastEditedDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdLabel1)
                    .addComponent(creationDate1))
                .addContainerGap())
        );

        createdDatePanel.setOpaque(false);

        createdLabel.setBackground(new java.awt.Color(204, 204, 204));
        createdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createdLabel.setForeground(new java.awt.Color(153, 153, 153));
        createdLabel.setText("created: ");

        creationDate.setBackground(new java.awt.Color(255, 255, 255));
        creationDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creationDate.setForeground(new java.awt.Color(153, 153, 153));
        creationDate.setText("24/3/2024, 3:30 p.m.");

        javax.swing.GroupLayout createdDatePanelLayout = new javax.swing.GroupLayout(createdDatePanel);
        createdDatePanel.setLayout(createdDatePanelLayout);
        createdDatePanelLayout.setHorizontalGroup(
            createdDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createdDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        createdDatePanelLayout.setVerticalGroup(
            createdDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createdDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createdDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdLabel)
                    .addComponent(creationDate))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Title");

        iconsPanel.setOpaque(false);

        todoBtn.setBorder(null);
        todoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/todoIcon.png"))); // NOI18N
        todoBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        todoBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        todoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoBtnActionPerformed(evt);
            }
        });

        cameraBtn.setBorder(null);
        cameraBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cameraIcon.png"))); // NOI18N
        cameraBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        cameraBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        cameraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraBtnActionPerformed(evt);
            }
        });

        paintBtn.setBorder(null);
        paintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paintIcon.png"))); // NOI18N
        paintBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        paintBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        paintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintBtnActionPerformed(evt);
            }
        });

        menuBtn.setBorder(null);
        menuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        menuBtn.setGradientColor1(new java.awt.Color(43, 41, 48));
        menuBtn.setGradientColor2(new java.awt.Color(43, 41, 48));
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iconsPanelLayout = new javax.swing.GroupLayout(iconsPanel);
        iconsPanel.setLayout(iconsPanelLayout);
        iconsPanelLayout.setHorizontalGroup(
            iconsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cameraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        iconsPanelLayout.setVerticalGroup(
            iconsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iconsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cameraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contentAreaScrollPane.setBorder(null);
        contentAreaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        contentAreaScrollPane.setHorizontalScrollBar(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        contentAreaScrollPane.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(createdDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastEditedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(iconsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(contentAreaScrollPane))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastEditedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createdDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void todoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todoBtnActionPerformed

    private void paintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintBtnActionPerformed

    private void cameraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cameraBtnActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customSwingComponents.GradientButton cameraBtn;
    private javax.swing.JScrollPane contentAreaScrollPane;
    private javax.swing.JPanel createdDatePanel;
    private javax.swing.JLabel createdLabel;
    private javax.swing.JLabel createdLabel1;
    private javax.swing.JLabel creationDate;
    private javax.swing.JLabel creationDate1;
    private javax.swing.JPanel iconsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel lastEditedDatePanel;
    private customSwingComponents.GradientButton menuBtn;
    private customSwingComponents.GradientButton paintBtn;
    private customSwingComponents.PanelBorder panelBorder1;
    private customSwingComponents.GradientButton todoBtn;
    // End of variables declaration//GEN-END:variables
}
