/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import models.TaskModel;

/**
 *
 * @author salma
 */
public class TaskPanel extends javax.swing.JPanel {

    private TaskModel task;
    /**
     * Creates new form taskPanel
     */
    public TaskPanel(TaskModel task) {
        this.task = task;
        initComponents();
    }
    
    public TaskPanel()
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskDone = new javax.swing.JCheckBox();
        taskString = new javax.swing.JTextField();

        setOpaque(false);

        taskDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskDoneActionPerformed(evt);
            }
        });

        taskString.setBackground(new java.awt.Color(20, 18, 24));
        taskString.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        taskString.setForeground(new java.awt.Color(255, 255, 255));
        taskString.setText("Task");
        taskString.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(taskString, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taskDone)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taskString)
                    .addComponent(taskDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void taskDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskDoneActionPerformed
        // TODO add your handling code here:
        task.SetTaskDone(taskDone.isSelected());
        System.out.println("task status: " + task.checked);
    }//GEN-LAST:event_taskDoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox taskDone;
    private javax.swing.JTextField taskString;
    // End of variables declaration//GEN-END:variables
}
