/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import DatabaseHelpers.DatabaseHelper;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import models.NoteModel;
import models.TaskModel;

/**
 *
 * @author salma
 */
public class TaskPanel extends javax.swing.JPanel {

    private TaskModel task;

    /**
     * Creates new form taskPanel
     */
    public TaskPanel(TaskModel task) {
        this.task = task;
        initComponents();
        if (this.task.getState()) {
            taskDone.doClick();
        }

        taskString.setText(this.task.getTask());
        taskString.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                task.setTask(taskString.getText());
                task.Save();
            }
        });
    }

    public TaskPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskDone = new javax.swing.JCheckBox();
        taskString = new customSwingComponents.StrikeThroughTextField();

        setOpaque(false);

        taskDone.setBackground(new java.awt.Color(208, 188, 255));
        taskDone.setForeground(new java.awt.Color(56, 30, 114));
        taskDone.setBorder(null);
        taskDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskDoneActionPerformed(evt);
            }
        });

        taskString.setBackground(new java.awt.Color(20, 18, 24));
        taskString.setBorder(null);
        taskString.setForeground(new java.awt.Color(255, 255, 255));
        taskString.setText("Task...");
        taskString.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        taskString.setLineColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskString, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(taskDone)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskDone))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void taskDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskDoneActionPerformed
        // TODO add your handling code here:
        task.setChecked(taskDone.isSelected());
        if(taskDone.isSelected())
        {
            taskString.drawStrikeThroughLine();
        }
        else
        {
            taskString.unDrawStrikeThroughLine();
        }
        task.Save();
    }//GEN-LAST:event_taskDoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox taskDone;
    private customSwingComponents.StrikeThroughTextField taskString;
    // End of variables declaration//GEN-END:variables
}
