/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject;

import customSwingComponents.ScrollBar;
import models.TaskModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author salma
 */
public class ToDoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ToDoPanel
     */
    public ToDoPanel() {
        initComponents();
        tasksScrollPanel.setVerticalScrollBar(new ScrollBar());
        tasksScrollPanel.getVerticalScrollBar().setBackground(getBackground());
        tasksScrollPanel.getViewport().setOpaque(false);
        tasksScrollPanel.setViewportBorder(null);
        tasksList.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new customSwingComponents.PanelBorder();
        tasksScrollPanel = new javax.swing.JScrollPane();
        tasksList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clearFinishedTasksBtn = new com.markbean.notes.customGUIComponents.RoundedButton();
        AddTaskBtn1 = new com.markbean.notes.customGUIComponents.RoundedButton();

        panelBorder1.setBackground(new java.awt.Color(20, 18, 24));
        panelBorder1.setForeground(new java.awt.Color(20, 18, 24));
        panelBorder1.setRadius(50);

        tasksScrollPanel.setBackground(new java.awt.Color(20, 18, 24));
        tasksScrollPanel.setBorder(null);
        tasksScrollPanel.setForeground(new java.awt.Color(20, 18, 24));
        tasksScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        tasksScrollPanel.setOpaque(false);

        tasksList.setBackground(new java.awt.Color(20, 18, 24));
        tasksList.setForeground(new java.awt.Color(20, 18, 24));
        tasksList.setOpaque(false);

        javax.swing.GroupLayout tasksListLayout = new javax.swing.GroupLayout(tasksList);
        tasksList.setLayout(tasksListLayout);
        tasksListLayout.setHorizontalGroup(
            tasksListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        tasksListLayout.setVerticalGroup(
            tasksListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        tasksScrollPanel.setViewportView(tasksList);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ToDo List");

        clearFinishedTasksBtn.setBackground(new java.awt.Color(51, 45, 65));
        clearFinishedTasksBtn.setBorder(null);
        clearFinishedTasksBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearFinishedTasksBtn.setText("Clear finished tasks");
        clearFinishedTasksBtn.setBorderColor(new java.awt.Color(51, 45, 65));
        clearFinishedTasksBtn.setBorderPainted(false);
        clearFinishedTasksBtn.setColor(new java.awt.Color(51, 45, 65));
        clearFinishedTasksBtn.setColorClick(new java.awt.Color(103, 0, 150));
        clearFinishedTasksBtn.setColorOver(new java.awt.Color(103, 80, 164));
        clearFinishedTasksBtn.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        clearFinishedTasksBtn.setRadius(15);
        clearFinishedTasksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFinishedTasksBtnActionPerformed(evt);
            }
        });

        AddTaskBtn1.setBackground(new java.awt.Color(51, 45, 65));
        AddTaskBtn1.setBorder(null);
        AddTaskBtn1.setForeground(new java.awt.Color(255, 255, 255));
        AddTaskBtn1.setText("Add Task");
        AddTaskBtn1.setBorderColor(new java.awt.Color(51, 45, 65));
        AddTaskBtn1.setBorderPainted(false);
        AddTaskBtn1.setColor(new java.awt.Color(51, 45, 65));
        AddTaskBtn1.setColorClick(new java.awt.Color(103, 0, 150));
        AddTaskBtn1.setColorOver(new java.awt.Color(103, 80, 164));
        AddTaskBtn1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        AddTaskBtn1.setRadius(15);
        AddTaskBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(AddTaskBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearFinishedTasksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tasksScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tasksScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearFinishedTasksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTaskBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearFinishedTasksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFinishedTasksBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearFinishedTasksBtnActionPerformed

    private void AddTaskBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskBtn1ActionPerformed
         tasksList.add(new TaskPanel(new TaskModel()));
         revalidate(); //to repaint the panel after adding new task
    }//GEN-LAST:event_AddTaskBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.markbean.notes.customGUIComponents.RoundedButton AddTaskBtn1;
    private com.markbean.notes.customGUIComponents.RoundedButton clearFinishedTasksBtn;
    private javax.swing.JLabel jLabel1;
    private customSwingComponents.PanelBorder panelBorder1;
    private javax.swing.JPanel tasksList;
    private javax.swing.JScrollPane tasksScrollPanel;
    // End of variables declaration//GEN-END:variables
}
