/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customSwingComponents;

/**
 *
 * @author salma
 */
public class Tag extends javax.swing.JPanel {

    /**
     * Creates new form Tag
     */
    public Tag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tag12 = new customSwingComponents.PanelBorder();
        bullet5 = new customSwingComponents.PanelBorder();
        tagName = new javax.swing.JLabel();
        taggedNotesNo = new javax.swing.JLabel();

        setOpaque(false);

        tag12.setBackground(new java.awt.Color(54, 52, 59));

        bullet5.setBackground(new java.awt.Color(202, 196, 208));
        bullet5.setRadius(50);

        javax.swing.GroupLayout bullet5Layout = new javax.swing.GroupLayout(bullet5);
        bullet5.setLayout(bullet5Layout);
        bullet5Layout.setHorizontalGroup(
            bullet5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        bullet5Layout.setVerticalGroup(
            bullet5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        tagName.setBackground(new java.awt.Color(202, 196, 208));
        tagName.setForeground(new java.awt.Color(202, 196, 208));
        tagName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tagName.setText("important ");

        taggedNotesNo.setBackground(new java.awt.Color(202, 196, 208));
        taggedNotesNo.setForeground(new java.awt.Color(202, 196, 208));
        taggedNotesNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taggedNotesNo.setText("100");

        javax.swing.GroupLayout tag12Layout = new javax.swing.GroupLayout(tag12);
        tag12.setLayout(tag12Layout);
        tag12Layout.setHorizontalGroup(
            tag12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tag12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bullet5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(tagName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(taggedNotesNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tag12Layout.setVerticalGroup(
            tag12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tag12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tag12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bullet5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tag12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taggedNotesNo)
                        .addComponent(tagName)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tag12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tag12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customSwingComponents.PanelBorder bullet;
    private customSwingComponents.PanelBorder bullet1;
    private customSwingComponents.PanelBorder bullet2;
    private customSwingComponents.PanelBorder bullet3;
    private customSwingComponents.PanelBorder bullet4;
    private customSwingComponents.PanelBorder bullet5;
    private customSwingComponents.PanelBorder tag10;
    private customSwingComponents.PanelBorder tag11;
    private customSwingComponents.PanelBorder tag12;
    private customSwingComponents.PanelBorder tag7;
    private customSwingComponents.PanelBorder tag8;
    private customSwingComponents.PanelBorder tag9;
    private javax.swing.JLabel tagName;
    private javax.swing.JLabel taggedNotesNo;
    // End of variables declaration//GEN-END:variables
}
